package com.example.photoreminder.data.sync
import android.content.Context
import android.content.SharedPreferences
import android.util.Log
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import androidx.work.workDataOf
import com.example.photoreminder.data.api.RetrofitInstance   // espone ApiService :contentReference[oaicite:0]{index=0}
import com.example.photoreminder.data.datastore.DataStoreManager
import com.example.photoreminder.data.local.MarkerDatabase
import com.example.photoreminder.data.local.SyncStatus
import com.example.photoreminder.data.model.toDto
import com.example.photoreminder.data.model.toEntity
import com.example.photoreminder.data.repository.MarkerRepository
import retrofit2.HttpException

class MarkerSyncWorker(
    appContext: Context,
    params: WorkerParameters
) : CoroutineWorker(appContext, params) {

    companion object {
        /** Nome usato da enqueueUniqueWork() per impedire job concorrenti */
        const val UNIQUE_WORK_NAME = "marker_sync_global"
        private const val INPUT_IS_MANUAL       = "isManual"
        private const val KEY_LAST_SYNC_PATTERN = "last_sync_time_%s"
        private const val PREFS_NAME            = "marker_sync_prefs"
        private const val TAG                   = "MarkerSyncWorker"
    }

    override suspend fun doWork(): Result {
        val manual = inputData.getBoolean(INPUT_IS_MANUAL, false)

        /* --- dipendenze (no Hilt) --- */
        val dao        = MarkerDatabase.getDatabase(applicationContext).markerDao()
        val repository = MarkerRepository(dao)
        val api        = RetrofitInstance.api                 // ApiService in singleton
        val prefs      = applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        return kotlin.runCatching {
            val username = DataStoreManager
                .getUsername(applicationContext)
                ?: error("Username not found; please log in again")

            val lastSync = prefs.lastSync(username)

            pushLocalChanges(repository, api)
            pullServerChanges(repository, api, lastSync)

            prefs.updateLastSync(username)
        }.fold(
            onSuccess = { success("Sync completata con successo", manual) },
            onFailure = { handleFailure(it, manual) }
        )
    }

    /* ---------------- PUSH ---------------- */

    private suspend fun pushLocalChanges(
        repository: MarkerRepository,
        api: com.example.photoreminder.data.api.ApiService
    ) {
        repository.getPendingForSync().forEach { entity ->
            kotlin.runCatching {
                when (entity.syncStatus) {
                    SyncStatus.LOCAL_ONLY -> {
                        val serverId = api.createMarker(entity.toDto()) //Server ID is the 'true' ID generated by the server that replaces the temporary UUID
                            .bodyOrThrow().marker.id
                        if (serverId != null) {
                            repository.replaceId(entity.id, serverId)
                        }
                        Log.d(TAG, "POST ok → id $serverId")
                    }
                    SyncStatus.DIRTY -> {
                        api.updateMarker(entity.id, entity.toDto()).bodyOrThrow()
                        repository.markSynced(entity.id)
                        Log.d(TAG, "PUT ok → id ${entity.id}")
                    }
                    SyncStatus.PENDING_DELETE -> {
                        api.deleteMarker(entity.id).bodyOrThrow()
                        repository.remove(entity.id)
                        Log.d(TAG, "DELETE ok → id ${entity.id}")
                    }
                    else -> Unit
                }
            }.onFailure { Log.e(TAG, "Push failed on id=${entity.id}", it) }
        }
    }

    /* ---------------- PULL ---------------- */

    private suspend fun pullServerChanges(
        repository: MarkerRepository,
        api: com.example.photoreminder.data.api.ApiService,
        updatedSince: Long
    ) {
        val list = api.getMarkers(updatedSince).bodyOrThrow().markers
        list.forEach { dto ->
            if (dto.deleted) {
                repository.remove(dto.id ?: return@forEach)
                Log.d(TAG, "Server says DELETED → id ${dto.id}")
            } else {
                repository.upsert(dto.toEntity())
                Log.d(TAG, "Upsert da server → id ${dto.id}")
            }
        }
    }

    /* ---------------- HELPERS ---------------- */

    private fun success(msg: String, manual: Boolean): Result =
        if (manual) Result.success(workDataOf("message" to msg)) else Result.success()

    private fun handleFailure(t: Throwable, manual: Boolean): Result {
        val msg = t.message ?: "Errore sconosciuto"
        return if (manual) Result.failure(workDataOf("errorMessage" to "Sync fallita: $msg"))
        else Result.retry()                 // lasciamo WorkManager gestire back-off
    }

    private fun SharedPreferences.lastSync(username: String) =
        getLong(KEY_LAST_SYNC_PATTERN.format(username), 0L)

    private fun SharedPreferences.updateLastSync(username: String) {
        edit().putLong(KEY_LAST_SYNC_PATTERN.format(username), System.currentTimeMillis()).apply()
    }

    /** Response: se non è 2xx o body nullo → HttpException */
    private fun <T> retrofit2.Response<T>.bodyOrThrow(): T =
        body() ?: throw HttpException(this)
}